#!/usr/bin/env python3
"""
PropPilot - LangGraph AI Real Estate Recommendation Pipeline
============================================================
This module loads the FAISS vector database generated by `proppilot_rag_ingestion.ipynb`
(using sentence-transformers/all-MiniLM-L6-v2 embeddings) and builds a LangGraph
conversational retrieval-augmented generation (RAG) agent using OpenRouter LLMs.
"""

import os
import sys
import json
import asyncio
from typing import List, Dict, Any, Optional, Sequence, Annotated
from typing_extensions import TypedDict

from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# LangChain & LangGraph Imports
# pyrefly: ignore [missing-import]
from langchain_core.messages import BaseMessage, HumanMessage, AIMessage, SystemMessage
# pyrefly: ignore [missing-import]
from langchain_core.documents import Document
# pyrefly: ignore [missing-import]
from langchain_community.vectorstores import FAISS
# pyrefly: ignore [missing-import]
from langchain_huggingface import HuggingFaceEmbeddings
# pyrefly: ignore [missing-import]
from langchain_openai import ChatOpenAI
# pyrefly: ignore [missing-import]
from langgraph.graph import StateGraph, START, END
# pyrefly: ignore [missing-import]
from langgraph.graph.message import add_messages


# ============================================================================
# CONFIGURATION
# ============================================================================

OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY")
if not OPENROUTER_API_KEY:
    # Attempt to load from .env file directly if not loaded yet
    load_dotenv(override=True)
    OPENROUTER_API_KEY = os.getenv("OPENROUTER_API_KEY", "")
OPENROUTER_BASE_URL = os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
# Free models on OpenRouter: openrouter/free, openrouter/auto, meta-llama/llama-3.3-70b-instruct:free, etc.
OPENROUTER_MODEL = os.getenv("OPENROUTER_MODEL", "openrouter/free")

EMBEDDING_MODEL_NAME = os.getenv(
    "EMBEDDING_MODEL_NAME", 
    "sentence-transformers/all-MiniLM-L6-v2"
)
FAISS_INDEX_DIR = os.getenv("FAISS_INDEX_PATH", ".")
FAISS_INDEX_NAME = os.getenv("FAISS_INDEX_NAME", "index")


# ============================================================================
# 1. VECTOR STORE LOADER
# ============================================================================

_vectorstore_cache: Optional[FAISS] = None

def get_vectorstore(index_dir: str = FAISS_INDEX_DIR, index_name: str = FAISS_INDEX_NAME) -> FAISS:
    """
    Loads and caches the FAISS vector store generated by proppilot_rag_ingestion.ipynb.
    Checks multiple search paths to find index.faiss and index.pkl gracefully.
    """
    global _vectorstore_cache
    if _vectorstore_cache is not None:
        return _vectorstore_cache

    candidate_dirs = [
        index_dir,
        os.path.dirname(os.path.abspath(__file__)),
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "faiss_index"),
        "./faiss_index",
        "."
    ]

    resolved_dir = None
    for d in candidate_dirs:
        faiss_file = os.path.join(d, f"{index_name}.faiss")
        pkl_file = os.path.join(d, f"{index_name}.pkl")
        if os.path.isfile(faiss_file) and os.path.isfile(pkl_file):
            resolved_dir = d
            break

    if not resolved_dir:
        raise FileNotFoundError(
            f"Could not find '{index_name}.faiss' and '{index_name}.pkl'. "
            f"Searched in: {candidate_dirs}"
        )

    print(f"📦 [PropPilot RAG] Loading FAISS index '{index_name}' from: {resolved_dir}")
    embeddings = HuggingFaceEmbeddings(model_name=EMBEDDING_MODEL_NAME)
    
    _vectorstore_cache = FAISS.load_local(
        folder_path=resolved_dir,
        embeddings=embeddings,
        index_name=index_name,
        allow_dangerous_deserialization=True  # safe: locally generated index
    )
    return _vectorstore_cache


# ============================================================================
# 2. OPENROUTER LLM FACTORY
# ============================================================================

def get_llm(model_name: str = OPENROUTER_MODEL, temperature: float = 0.3, streaming: bool = False) -> ChatOpenAI:
    """
    Initializes a ChatOpenAI client connected to OpenRouter API.
    """
    return ChatOpenAI(
        model=model_name,
        openai_api_key=OPENROUTER_API_KEY,
        openai_api_base=OPENROUTER_BASE_URL,
        temperature=temperature,
        streaming=streaming,
        default_headers={
            "HTTP-Referer": "https://github.com/srishanbangera-sys/LangGraph_Estate_Recommendation",
            "X-Title": "PropPilot Real Estate AI",
        }
    )


# ============================================================================
# 3. LANGGRAPH STATE DEFINITION
# ============================================================================

class AgentState(TypedDict):
    """The state shared across all nodes in the LangGraph pipeline."""
    messages: Annotated[Sequence[BaseMessage], add_messages]
    query: str
    retrieved_docs: List[Document]
    retrieved_context: str
    property_metadata: List[Dict[str, Any]]
    final_answer: str


# ============================================================================
# 4. LANGGRAPH NODES
# ============================================================================

SYSTEM_PROMPT = """You are **PropPilot AI**, an elite and knowledgeable real estate advisory intelligence system.
Your mission is to help users find their ideal homes, villas, and apartments based strictly on verified property listings in your database.

Guidelines:
1. **Grounded In Data**: Base your recommendations primarily on the retrieved property listings provided below. Mention property titles, locations, price points, bedroom/bathroom configurations, and distinctive amenities directly from the data.
2. **Actionable & Structured**: Format your response with clear markdown headings, bulleted property highlights, and personalized reasoning for why each listing fits the user's inquiry.
3. **Honest & Helpful**: If no exact match exists for a specific parameter, suggest the closest available properties from the context.
4. **Follow-up Next Steps**: Conclude with a helpful question or suggested next steps (e.g., scheduling a virtual viewing, filtering by price, or exploring nearby neighborhoods).

Retrieved Property Database Listings:
{context}
"""

def extract_query(messages: Sequence[BaseMessage]) -> str:
    """Extracts the latest user query from the messages sequence."""
    for msg in reversed(messages):
        if isinstance(msg, HumanMessage) or getattr(msg, "type", "") == "human":
            return msg.content if isinstance(msg.content, str) else str(msg.content)
    return ""


def parse_property_doc(doc: Document) -> Dict[str, Any]:
    """Helper to parse key property metadata from a CSVLoader document."""
    data = {"raw": doc.page_content}
    lines = doc.page_content.split("\n")
    for line in lines:
        if ":" in line:
            parts = line.split(":", 1)
            key = parts[0].strip().lower().replace(" ", "_")
            val = parts[1].strip()
            data[key] = val
    return data


def retrieve_properties_node(state: AgentState) -> Dict[str, Any]:
    """
    Node 1: Retrieves the most relevant property documents from the FAISS vector database.
    """
    user_query = state.get("query") or extract_query(state.get("messages", []))
    if not user_query:
        user_query = "modern luxury home in UK"

    print(f"🔍 [retrieve_properties_node] Searching FAISS for: '{user_query}'")
    vectorstore = get_vectorstore()
    
    # Retrieve top 4 most relevant property chunks
    docs = vectorstore.similarity_search(user_query, k=4)
    print(f"   Found {len(docs)} matching property records.")

    # Format context string for the LLM
    context_chunks = []
    parsed_metadata = []
    for i, doc in enumerate(docs, 1):
        context_chunks.append(f"--- Property Listing #{i} ---\n{doc.page_content}")
        parsed_metadata.append(parse_property_doc(doc))

    retrieved_context = "\n\n".join(context_chunks)

    return {
        "query": user_query,
        "retrieved_docs": docs,
        "retrieved_context": retrieved_context,
        "property_metadata": parsed_metadata,
    }


def generate_recommendations_node(state: AgentState) -> Dict[str, Any]:
    """
    Node 2: Passes the retrieved properties and conversation history to the OpenRouter LLM.
    """
    retrieved_context = state.get("retrieved_context", "No property listings found.")
    messages = state.get("messages", [])

    system_message = SystemMessage(
        content=SYSTEM_PROMPT.format(context=retrieved_context)
    )

    prompt_messages = [system_message]
    for msg in messages:
        if isinstance(msg, (HumanMessage, AIMessage)):
            prompt_messages.append(msg)

    # If messages was empty or lacked HumanMessage, append the query
    if not any(isinstance(m, HumanMessage) for m in prompt_messages):
        prompt_messages.append(HumanMessage(content=state.get("query", "Find recommendations")))

    print(f"🤖 [generate_recommendations_node] Invoking LLM ({OPENROUTER_MODEL})...")
    llm = get_llm()

    try:
        response = llm.invoke(prompt_messages)
        answer_text = response.content if isinstance(response.content, str) else str(response.content)
    except Exception as e:
        print(f"⚠️ Primary model invocation failed: {e}. Trying fallback model 'openrouter/auto'...")
        try:
            fallback_llm = get_llm(model_name="openrouter/auto")
            response = fallback_llm.invoke(prompt_messages)
            answer_text = response.content if isinstance(response.content, str) else str(response.content)
        except Exception as fallback_err:
            answer_text = (
                f"I found matching properties in our database, but encountered a connection "
                f"issue with the OpenRouter API: {fallback_err}\n\n"
                f"Here are the top listings retrieved directly from the dataset:\n\n"
                f"{retrieved_context}"
            )

    return {
        "messages": [AIMessage(content=answer_text)],
        "final_answer": answer_text
    }


# ============================================================================
# 5. COMPILE LANGGRAPH PIPELINE
# ============================================================================

def build_proppilot_graph():
    """
    Builds and compiles the LangGraph StateGraph pipeline:
    START -> retrieve_properties -> generate_recommendations -> END
    """
    builder = StateGraph(AgentState)

    builder.add_node("retrieve_properties", retrieve_properties_node)
    builder.add_node("generate_recommendations", generate_recommendations_node)

    builder.add_edge(START, "retrieve_properties")
    builder.add_edge("retrieve_properties", "generate_recommendations")
    builder.add_edge("generate_recommendations", END)

    return builder.compile()


# Global compiled graph instance
proppilot_agent = build_proppilot_graph()


# ============================================================================
# 6. HIGH-LEVEL QUERY API
# ============================================================================

def run_query(query: str, history: Optional[List[Dict[str, str]]] = None) -> Dict[str, Any]:
    """
    Synchronous helper to execute a query turn through the LangGraph pipeline.
    
    :param query: The user's prompt (e.g., "Find luxury villas in London with pool")
    :param history: Optional list of past messages [{'role': 'user'|'assistant', 'content': '...'}]
    :return: Dict with 'answer', 'properties', and 'query'
    """
    messages: List[BaseMessage] = []
    if history:
        for item in history:
            role = item.get("role")
            content = item.get("content", "")
            if role == "user":
                messages.append(HumanMessage(content=content))
            elif role == "assistant":
                messages.append(AIMessage(content=content))

    messages.append(HumanMessage(content=query))

    initial_state: AgentState = {
        "messages": messages,
        "query": query,
        "retrieved_docs": [],
        "retrieved_context": "",
        "property_metadata": [],
        "final_answer": "",
    }

    final_state = proppilot_agent.invoke(initial_state)

    return {
        "answer": final_state.get("final_answer", ""),
        "properties": final_state.get("property_metadata", []),
        "query": query
    }


async def stream_query(query: str, history: Optional[List[Dict[str, str]]] = None):
    """
    Asynchronous generator yielding streamed tokens and tool events.
    """
    messages: List[BaseMessage] = []
    if history:
        for item in history:
            role = item.get("role")
            content = item.get("content", "")
            if role == "user":
                messages.append(HumanMessage(content=content))
            elif role == "assistant":
                messages.append(AIMessage(content=content))

    messages.append(HumanMessage(content=query))

    initial_state: AgentState = {
        "messages": messages,
        "query": query,
        "retrieved_docs": [],
        "retrieved_context": "",
        "property_metadata": [],
        "final_answer": "",
    }

    # Execute graph nodes and stream updates
    async for event in proppilot_agent.astream(initial_state):
        yield event


# ============================================================================
# 7. FASTAPI SERVER FOR FRONTEND / API STREAMING
# ============================================================================

def create_api_app():
    """Builds a FastAPI app with SSE streaming support for the React frontend."""
    from fastapi import FastAPI, Request
    from fastapi.middleware.cors import CORSMiddleware
    from fastapi.responses import StreamingResponse, JSONResponse
    from pydantic import BaseModel

    api = FastAPI(
        title="PropPilot LangGraph AI API",
        description="Real Estate Recommendation Agent with FAISS Vector Search & OpenRouter LLM",
        version="1.0.0"
    )

    api.add_middleware(
        CORSMiddleware,
        allow_origins=["*"],
        allow_credentials=True,
        allow_methods=["*"],
        allow_headers=["*"],
    )

    class ChatInput(BaseModel):
        message: Optional[str] = None
        input: Optional[Dict[str, Any]] = None
        history: Optional[List[Dict[str, str]]] = None
        filters: Optional[Dict[str, Any]] = None

    @api.get("/health")
    def health_check():
        return {"status": "ok", "agent": "PropPilot", "model": OPENROUTER_MODEL}

    @api.post("/api/chat")
    def chat_endpoint(payload: ChatInput):
        # Support both payload formats ({ message } or { input: { messages: [...] } })
        user_message = payload.message
        history = payload.history or []
        if not user_message and payload.input:
            msgs = payload.input.get("messages", [])
            if msgs:
                user_message = msgs[-1].get("content", "")
                history = msgs[:-1]

        if not user_message:
            return JSONResponse({"error": "No message provided"}, status_code=400)

        result = run_query(user_message, history)
        return result

    @api.post("/api/chat/stream")
    @api.post("/stream")
    async def stream_endpoint(payload: ChatInput):
        """Streams Server-Sent Events (SSE) directly to the React frontend."""
        user_message = payload.message
        history = payload.history or []
        if not user_message and payload.input:
            msgs = payload.input.get("messages", [])
            if msgs:
                user_message = msgs[-1].get("content", "")
                history = msgs[:-1]

        if not user_message:
            user_message = "Find real estate recommendations in United Kingdom"

        async def event_generator():
            # Step 1: Run retrieval & emit matching property notification
            vectorstore = get_vectorstore()
            docs = vectorstore.similarity_search(user_message, k=4)
            retrieved_props = [parse_property_doc(d) for d in docs]
            
            # Emit tool call event
            yield f"data: {json.dumps({'tool_call': {'name': 'vector_search', 'args': {'query': user_message, 'found': len(docs)}}})}\n\n"
            await asyncio.sleep(0.05)

            # Step 2: Stream tokens from LLM
            llm = get_llm(streaming=True)
            system_message = SystemMessage(
                content=SYSTEM_PROMPT.format(
                    context="\n\n".join([f"Listing #{i+1}:\n{d.page_content}" for i, d in enumerate(docs)])
                )
            )
            prompt_msgs = [system_message, HumanMessage(content=user_message)]

            async for chunk in llm.astream(prompt_msgs):
                token = chunk.content if hasattr(chunk, "content") else str(chunk)
                if token:
                    yield f"data: {json.dumps({'token': token})}\n\n"

            # Step 3: Complete event with property metadata
            yield f"data: {json.dumps({'done': True, 'properties': retrieved_props})}\n\n"

        return StreamingResponse(event_generator(), media_type="text/event-stream")

    # ========================================================================
    # CROSS-DEVICE REAL-TIME STATE SYNCHRONIZATION
    # ========================================================================
    from fastapi import WebSocket, WebSocketDisconnect
    import time

    STATE_FILE = "synced_global_state.json"

    def load_persisted_state():
        if os.path.exists(STATE_FILE):
            try:
                with open(STATE_FILE, "r") as f:
                    return json.load(f)
            except Exception:
                pass
        return {
            "activeFilters": {},
            "messages": [],
            "savedPropertyIds": [],
            "currentMapLocation": {"lat": 12.9141, "lng": 74.8560, "zoom": 12},
            "selectedPropertyId": None,
            "role": "user",
            "activeTab": "chat",
            "updatedAt": None,
            "sourceDevice": "server_init"
        }

    def save_persisted_state(state):
        try:
            with open(STATE_FILE, "w") as f:
                json.dump(state, f, indent=2)
        except Exception as e:
            print(f"Error saving persisted state: {e}")

    class SyncConnectionManager:
        def __init__(self):
            self.active_connections: Dict[str, List[WebSocket]] = {}

        async def connect(self, websocket: WebSocket, session_id: str):
            await websocket.accept()
            if session_id not in self.active_connections:
                self.active_connections[session_id] = []
            self.active_connections[session_id].append(websocket)

        def disconnect(self, websocket: WebSocket, session_id: str):
            if session_id in self.active_connections:
                if websocket in self.active_connections[session_id]:
                    self.active_connections[session_id].remove(websocket)
                if not self.active_connections[session_id]:
                    del self.active_connections[session_id]

        async def broadcast(self, message: dict, session_id: str, exclude_socket: Optional[WebSocket] = None):
            if session_id in self.active_connections:
                for connection in list(self.active_connections[session_id]):
                    if connection != exclude_socket:
                        try:
                            await connection.send_json(message)
                        except Exception:
                            self.disconnect(connection, session_id)

    sync_manager = SyncConnectionManager()
    current_global_state = load_persisted_state()

    @api.get("/api/sync/state")
    def get_sync_state(sessionId: str = "default_session"):
        return {"sessionId": sessionId, "state": current_global_state}

    @api.post("/api/sync/state")
    async def post_sync_state(payload: Dict[str, Any], sessionId: str = "default_session"):
        nonlocal current_global_state
        state_update = payload.get("state", payload)
        source = payload.get("source", "rest_client")
        current_global_state.update(state_update)
        current_global_state["updatedAt"] = time.time()
        current_global_state["sourceDevice"] = source
        save_persisted_state(current_global_state)

        await sync_manager.broadcast({
            "type": "STATE_BROADCAST",
            "state": current_global_state,
            "source": source,
            "timestamp": current_global_state["updatedAt"]
        }, session_id=sessionId)

        return {"status": "ok", "synced": True, "state": current_global_state}

    @api.websocket("/ws/sync/{session_id}")
    async def websocket_sync_endpoint(websocket: WebSocket, session_id: str):
        nonlocal current_global_state
        await sync_manager.connect(websocket, session_id)
        try:
            # Send current synchronized state upon connection
            await websocket.send_json({
                "type": "INITIAL_STATE",
                "state": current_global_state,
                "clientCount": len(sync_manager.active_connections.get(session_id, []))
            })

            while True:
                data = await websocket.receive_json()
                msg_type = data.get("type", "STATE_UPDATE")
                payload_state = data.get("payload", {})
                source = data.get("source", "unknown_device")

                current_global_state.update(payload_state)
                current_global_state["updatedAt"] = time.time()
                current_global_state["sourceDevice"] = source
                save_persisted_state(current_global_state)

                # Real-time broadcast to all other devices (laptop <-> phone)
                await sync_manager.broadcast({
                    "type": "REMOTE_STATE_UPDATED",
                    "state": current_global_state,
                    "source": source,
                    "timestamp": current_global_state["updatedAt"]
                }, session_id=session_id, exclude_socket=websocket)

        except WebSocketDisconnect:
            sync_manager.disconnect(websocket, session_id)
        except Exception:
            sync_manager.disconnect(websocket, session_id)

    return api


# ============================================================================
# 8. INTERACTIVE CLI RUNNER
# ============================================================================

def interactive_cli():
    """Runs an interactive command-line interface for immediate testing."""
    print("=" * 65)
    print("  🏡 PropPilot — LangGraph Real Estate Recommendation Agent")
    print("=" * 65)
    print(f"  • LLM:         {OPENROUTER_MODEL} via OpenRouter")
    print(f"  • Embeddings:  {EMBEDDING_MODEL_NAME}")
    print(f"  • Vectorstore: FAISS ({FAISS_INDEX_NAME}.faiss + {FAISS_INDEX_NAME}.pkl)")
    print("=" * 65)
    print("  Type your property questions below (or 'exit' to quit).\n")

    # Pre-warm vectorstore
    try:
        get_vectorstore()
        print("✅ FAISS vector database loaded successfully.\n")
    except Exception as e:
        print(f"❌ Failed to load FAISS index: {e}\n")
        return

    chat_history: List[Dict[str, str]] = []

    while True:
        try:
            user_input = input("\n👤 You: ").strip()
            if not user_input:
                continue
            if user_input.lower() in ("exit", "quit", "q"):
                print("\n👋 Goodbye! Happy property hunting.\n")
                break

            print("\n🤖 PropPilot is searching vector database & generating recommendations...")
            result = run_query(user_input, chat_history)

            print("\n" + result["answer"])

            # Store in history
            chat_history.append({"role": "user", "content": user_input})
            chat_history.append({"role": "assistant", "content": result["answer"]})

        except KeyboardInterrupt:
            print("\n\nSession terminated by user.")
            break
        except Exception as e:
            print(f"\n⚠️ Error: {e}")


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="PropPilot LangGraph Real Estate Agent")
    parser.add_argument("--serve", action="store_true", help="Start the FastAPI REST/SSE backend server")
    parser.add_argument("--port", type=int, default=8000, help="Port to run API server on (default: 8000)")
    parser.add_argument("--host", type=str, default="0.0.0.0", help="Host for API server (default: 0.0.0.0)")
    parser.add_argument("--query", type=str, default=None, help="Execute a single one-shot query")

    args = parser.parse_args()

    if args.serve:
        import uvicorn
        app = create_api_app()
        print(f"🚀 Starting PropPilot FastAPI server on http://{args.host}:{args.port}")
        print(f"   • Health Check: http://{args.host}:{args.port}/health")
        print(f"   • Chat API:     http://{args.host}:{args.port}/api/chat")
        print(f"   • SSE Stream:   http://{args.host}:{args.port}/api/chat/stream")
        uvicorn.run(app, host=args.host, port=args.port)
    elif args.query:
        res = run_query(args.query)
        print(res["answer"])
    else:
        interactive_cli()
